export const USER_LOGIN = 'life/USER_LOGIN'
export const USER_LOGIN_REQUESTED = 'life/USER_LOGIN_REQUESTED'
export const USER_LOGIN_FAILED = 'life/USER_LOGIN_FAILED'
export const USER_LOGIN_SUCCEEDED = 'life/USER_LOGIN_SUCCEEDED'
